### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Review by tituspijean — APPROVED** [review]
Per https://github.com/YunoHost-Apps/bludit_ynh/pull/18, LGTM!

**Comment by tituspijean** [comment]
Hum @ericgaspar ... I have just realized that's a beta version. Do we actually want to merge it?

**Comment by ericgaspar** [comment]
Final release must be around the corner... let's wait

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
